#!/usr/bin/env python
import sys

import tools.git as git
import tools.jenkins as jenkins


def main(stdin, config, *args):
    jenkins.build_jobs(config.get('hooks.jenkins-jobs'))

if __name__ == '__main__':
    main(sys.stdin, git.config(), *sys.argv[1:])
