#!/usr/bin/env python
import sys
import subprocess

from jenkins_builder import Jenkins


def main(stdin, config, *args):
    for jobname in config.get('hooks.jenkins-jobs', '').split(','):
        jobname = jobname.strip()
        Jenkins(jobname).build()

if __name__ == '__main__':
    config = {}
    for line in subprocess.Popen(['git', 'config', '--list'], stdout=subprocess.PIPE).communicate()[0].splitlines():
        k, v = line.split('=', 1)
        config[k] = v
    main(sys.stdin, config, *sys.argv[1:])
